[tool.poetry]
name = "mirageoscience-pre_commit_hooks"

version = "0.1.0"

license = "MIT"
description = ""
repository = "https://github.com/MiraGeoscience/pre-commit-hooks"
authors = ["Mira Geoscience <support@mirageoscience.com>"]
readme = "README.rst"

include = [
    "LICENSE",
    "README.rst"
]

[tool.poetry.dependencies]
python = "^3.12"

[tool.poetry.scripts]
check_copyright = "mirageoscience-pre_commit_hooks.check_copyright:main"
git_message_hook = "mirageoscience-pre_commit_hooks.git_message_hook:main"

[tool.flit.module]
name = "mirageoscience-pre_commit_hooks"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"